org: algono
app: feed-the-parrot-auth
service: feed-the-parrot-auth

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  login:
    handler: app/handler.login
    events:
      - http:
          path: login/{id}
          method: get
